### ISSUE TITLE
File_Blocks_Index: Unsupported index file format version

### ISSUE THREAD

**Issue by rakesh-nd** [wiktorn/Overpass-API#104]
We are getting below error with 'latest' docker image from dockerhub:

**Error: runtime error: open64: 0 Success /db/db/nodes.bin.idx File_Blocks_Index: Unsupported index file format version**

Is there a way a fix this issue ?

**Comment by Zaczero** [comment]
I thought the data got corrupted, re-cloned from scratch, the issue still persists.

**Comment by ikespand** [comment]
This generally happens when the version is mismatched between built database and deployed version for overpass. If you have tried the latest docker image and `clone` as `OVERPASS_MODE ` (for entire planet file) then this error will occur at present. Because, latest of this docker is v.0.7.58 and current clone database was built with v0.7.60. Hopefully @wiktorn can create a new docker build. Otherwise, you can create a build yourself by followin [this ](https://github.com/wiktorn/Overpass-API/blob/master/build.sh) and try it out.

**Comment by rakesh-nd** [comment]
The latest docker image is working, Thanks !
