### ISSUE TITLE
replicate_id is not available at given path expected by clone script

### ISSUE THREAD

**Issue by jenishshah671993** [wiktorn/Overpass-API#93]
Hi Team,
I have been trying cloning mechanism and it tries to copy replicate_id file from path EXEC_DIR/db/replicate_id but it actually reside on EXEC_DIR/replicate_id. So it's not getting copied, So when I execute download clone script it does not work as it does get replicate_id to start with.
Could you please help me with him?

below is the structure where replicate_id resides

<img width="712" alt="Screenshot 2022-04-25 at 10 27 13 AM" src="https://user-images.githubusercontent.com/13361410/165230215-fc59afaf-7ca4-407f-abe0-a54619d4e12b.png">

**Comment by jenishshah671993** [comment]
I have also raised issue to overpass team and they mentioned that docker has script call init_done which they don't have
https://github.com/drolbr/Overpass-API/issues/663

**Comment by wiktorn** [comment]
I don't know what you are trying to run and what kind of error you're running into.

`docker-entrypoint.sh` calls `/app/bin/download_clone.sh --db-dir=/db/db`

Which, in this [line](https://github.com/drolbr/Overpass-API/blob/master/src/bin/download_clone.sh#L110) fetches `replicate_id` into `/db/db/replicate_id`.

When we move back to `docker-entrypoint.sh` its coping `replicate_id` one folder up:
```
cp /db/db/replicate_id /db/replicate_id
```

In the screenshot you've provided, you have both files present:
* `/db/replicate_id`
* `/db/db/replicate_id`

So sorry, don't understand what the issue is about.
